spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://ec2-54-73-110-26.eu-west-1.compute.amazonaws.com:5432/dci1e20uson1qf
spring.datasource.username=xcwhppptvocfex
spring.datasource.password=50a059219b443a4b579addc24d1a2b15f92fb72ebe074932b84f5ca84cbc4b49

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQL94Dialect

#server.error.include-message = always


